[phases.setup]
nixPkgs = ['nodejs_20', 'npm']

[phases.install]
cmds = ['npm ci --include=dev']

[phases.build]
cmds = ['echo "Skipping Vite build - using development server in production"']

[start]
cmd = 'NODE_ENV=production npx tsx server/index.ts'